### ISSUE TITLE
Runtime error when inserting models with Option<String> fields and a prefix index.

### ISSUE THREAD

**Issue by auxesis** [cipherstash/cipherstash-dynamodb#63]
As reported privately by @nicklaswj:

> I get an runtime error `InternalError(EncryptedDdb(CipherStash(PutError(Seal(InvalidCiphertext("Invalid index term"))))))` when I try to insert a specific model with CipherStash. I have found out it’s because I have a field in my model that’s an `Option<String>` and I have a `prefix` index on it.
>
> If this is intended behaviour, could we change it such that CipherStash just doesn’t create index rows for optional fields when they are `None` instead of returning an error?

**Comment by coderdan** [comment]
This issue has been fixed in [cipherstash-client-0.12.2](https://crates.io/crates/cipherstash-client/0.12.2).

Please run the following to update:
```
cargo update cipherstash-client
```
